# Generated by Django 2.1.4 on 2019-03-17 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0006_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='buying_type',
            field=models.CharField(choices=[('Self-delivery', 'Self-delivery'), ('Delivery', 'Delivery')], default='Self-delivery', max_length=40),
        ),
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='ecomapp.Cart'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('accepted for processing', 'accepted for processing'), ('processing', 'processing'), ('paid', 'paid')], default='accepted for processing', max_length=100),
        ),
    ]
