# Generated by Django 2.1.4 on 2019-03-19 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0007_auto_20190318_0043'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiddlwareNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber', models.CharField(max_length=40)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ecomapp.Product')),
            ],
        ),
    ]
